# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: 🎉 Exciting New Features
      labels:
        - Semver-Minor
        - enhancement
        - improvement
        - feature
    - title: 📜 Documentation
      labels:
        - documentation
    - title: 🐞 Bug Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: 💡 Other Changes
      labels:
        - "*"
