# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html
variables:
  JENKINS_BUILD_NUMBER:
      value: '140'
      description: build number in jenkins
  JENKINS_USER:
      description: >
        the username with which the jenkins artifact is
        downloaded (eventually, this will be a project/group variable)
  JENKINS_PASSWORD:
      description: >
        the password with which the jenkins artifact is
        downloaded (eventually, this will be a project/group variable)
  TOMCAT_USER:
      description: >
        the username with which the war is deployed to tomcat is
        downloaded (eventually, this will be a project/group variable)
  TOMCAT_PASSWORD:
      description: >
        the password with which the war is deployed to tomcat is
        downloaded (eventually, this will be a project/group variable)   


stages:         
  - build
  - deploy

copy-war-from-jenkins:
  stage: build
  tags: ["dind"]
  image: alpine/curl:8.12.1

  variables:
    JENKINS_URL: "http://gene-expression.ebi.ac.uk/jenkins"
    JENKINS_JOB: "Single%20Cell%20Expression%20Atlas%20%E2%80%93%20Develop"
    JENKINS_BRANCH: develop
  when: manual    
  script:
    - >
      curl -u "${JENKINS_USER}:${JENKINS_PASSWORD}" 
      --fail
      "${JENKINS_URL}/job/${JENKINS_JOB}/job/${JENKINS_BRANCH}/${JENKINS_BUILD_NUMBER}/artifact/webapps/gxa%23sc.war" 
      --output "./gxa#sc.war"
  artifacts:
    paths:
      - "./gxa#sc.war"

deploy-test: 
  variables:
    TOMCAT_URL: "http://wp-np2-21:8080"
  environment:
    name: test
    url: https://www-test.ebi.ac.uk/gxa/sc/
  when: manual
  manual_confirmation: 'Are you sure you want to deploy to test?'
  extends: .deploy-template

deploy-staging: 
  variables:
    TOMCAT_URL: "http://wp-p1m2-99:8080"
  environment:
    name: staging
    url: https://wwwdev.ebi.ac.uk/gxa/sc/
  when: manual
  manual_confirmation: 'Are you sure you want to deploy to staging?'
  extends: .deploy-template

deploy-fallback: 
  parallel:
    matrix:
      TOMCAT_URL: ["http://wp-p2m-8e:8080", "http://wp-p2m-8f:8080"]
  environment:
    name: fallback/$TOMCAT_URL
    url: $TOMCAT_URL/gxa/sc/
  when: manual
  manual_confirmation: 'Are you sure you want to deploy to fallback?'
  extends: .deploy-template

deploy-prod: 
  parallel:
    matrix:
      TOMCAT_URL: ["http://wp-p1m-8e:8080", "http://wp-p1m-8f:8080"]
  environment:
    name: prod/$TOMCAT_URL
    url: $TOMCAT_URL/gxa/sc/
  when: manual
  manual_confirmation: 'Are you sure you want to deploy to prod?'
  extends: .deploy-template
  
  
.deploy-template:
  stage: deploy
  tags: ["dind"]
  image: alpine/curl:8.12.1
  script:
    - >
      curl -u "${TOMCAT_USER}:${TOMCAT_PASSWORD}" 
      -i --fail -X PUT 
      "${TOMCAT_URL}/manager/text/deploy?path=/gxa/sc&update=true"
      --upload-file "./gxa#sc.war"
    - >
      curl -u "${TOMCAT_USER}:${TOMCAT_PASSWORD}" 
      -i --fail 
      "${TOMCAT_URL}/manager/text/list"
      | grep "/gxa/sc" | grep running
      || { echo "App /gxa/sc not found or not running"; exit 1; }

