version: "3.6"

services:
  #### SolrCloud
  zk-1:
    image: zookeeper:3.4.14
    container_name: scxa-zk-1
    networks:
      - scxa
    restart: always
    volumes:
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/zoo1/data:/data
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/zoo1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=scxa-zk-2:2888:3888 server.3=scxa-zk-3:2888:3888

  zk-2:
    image: zookeeper:3.4.14
    container_name: scxa-zk-2
    networks:
      - scxa
    restart: always
    volumes:
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/zoo2/data:/data
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/zoo2/datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=scxa-zk-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=scxa-zk-3:2888:3888

  zk-3:
    image: zookeeper:3.4.14
    container_name: scxa-zk-3
    networks:
      - scxa
    restart: always
    volumes:
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/zoo3/data:/data
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/zoo3/datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=scxa-zk-1:2888:3888 server.2=scxa-zk-2:2888:3888 server.3=0.0.0.0:2888:3888

  solrcloud-1:
    image: solr:7.1
    container_name: scxa-solrcloud-1
    networks:
      - scxa
    ports:
      - "8983:8983"
    volumes:
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/solr1:/var/solr
    environment:
      - SOLR_HOME=/var/solr
      - SOLR_HEAP=2g
      - SOLR_OPTS=-Denable.runtime.lib=true
      - ZK_HOST=scxa-zk-1:2181,scxa-zk-2:2181,scxa-zk-3:2181
    depends_on:
      - zk-1
      - zk-2
      - zk-3

  solrcloud-2:
    image: solr:7.1.0
    container_name: scxa-solrcloud-2
    networks:
      - scxa
    ports:
      - "8984:8983"
    volumes:
      - /home/alf/Projects/atlas/integration-test-data/solrcloud/scxa/solr2:/var/solr
    environment:
      - SOLR_HOME=/var/solr
      - SOLR_HEAP=2g
      - SOLR_OPTS=-Denable.runtime.lib=true
      - ZK_HOST=scxa-zk-1:2181,scxa-zk-2:2181,scxa-zk-3:2181
    depends_on:
      - zk-1
      - zk-2
      - zk-3

  #### Database
  postgres:
    image: postgres:10-alpine
    container_name: $POSTGRES_HOST
    networks:
      - scxa
    restart: always
    command: -c max_wal_size=2GB
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: atlasprd3
      POSTGRES_PASSWORD: atlasprd3
      POSTGRES_DB: gxpscxadev
    ports:
      - "5432:5432"
    volumes:
      - /home/alf/Projects/atlas/integration-test-data/postgres/scxa:/var/lib/postgresql/data/pgdata

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/gxpscxadev -schemas=atlasprd3 -user=atlasprd3 -password=atlasprd3 -connectRetries=60 migrate
    volumes:
      - ../atlas-web-core/src/test/resources/schemas/flyway/scxa/:/flyway/sql
    depends_on:
      - postgres

  #### Web server and filesystem
  tomcat:
    image: tomcat:8-jdk11
    container_name: scxa-tomcat
    networks:
      - scxa
    environment:
      JPDA_ADDRESS: "*:8000"
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/usr/local/tomcat/webapps
      - /home/alf/Projects/atlas/integration-test-data/filesystem:/atlas-data
      - scxa_tomcat_conf:/usr/local/tomcat/conf
    depends_on:
      - postgres
      - solrcloud-1
      - solrcloud-2

volumes:
  tomcat-conf:
    name: scxa-tomcat-conf

networks:
  scxa:
    name: scxa
