apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-gene-expression
spec:
  serviceAccountName: admin-jenkins-gene-expression
  # If we set workspaceVolume dynamicPVC() or workspaceVolume persistentVolumeClaimWorkspaceVolume() we need to add a
  # fsGroup 1000 to make the /home/jenkins/agent directory writable. Otherwise we get the following exception in the
  # jnlp container:
  # Exception in thread "main" java.io.IOException: The specified working directory should be fully accessible to the remoting executable (RWX): /home/jenkins/agent
  # The securityContext in the pod is inherited, as it becomes the default pod template
  securityContext:
    fsGroup: 1000
  containers:
    - name: "kubectl"
      image: bitnami/kubectl
      command: ["/bin/sh"]
      args: ["-c", "kubectl scale --replicas=3 solrcloud/scxa"]
      resources:
        requests:
          memory: "0.5Gi"
        limits:
          memory: "0.5Gi"
    - name: jnlp
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "512Mi"
    - name: openjdk
      image: openjdk:11
      resources:
        requests:
          memory: "1Gi"
          ephemeral-storage: "5Gi"
        limits:
          memory: "1.5Gi"
      env:
      - name: GRADLE_OPTS
        value: "-Dorg.gradle.daemon=false"
      - name: GRADLE_RO_DEP_CACHE
        value: "/root/gradle-ro-dep-cache"
      command:
      - sleep
      args:
      - 99d
      volumeMounts:
        - mountPath: /test-data/scxa
          name: scxa-ci-data
        - mountPath: /test-data/bioentity_properties
          name: bioentity-properties
        - mountPath: /root/gradle-ro-dep-cache
          name: gradle-ro-dep-cache
          readOnly: true
        - mountPath: /root/.gradle/wrapper
          name: openjdk-root-gradle-wrapper
    - name: postgres
      image: postgres:10-alpine
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
  volumes:

    - name: scxa-ci-data
      persistentVolumeClaim:
        claimName: sc-test-experiments-claim
    - name: bioentity-properties
      persistentVolumeClaim:
        claimName: bioentity-properties-claim
    - name: gradle-ro-dep-cache
      persistentVolumeClaim:
        claimName: gradle-ro-dep-cache-claim
    - name: openjdk-root-gradle-wrapper
      persistentVolumeClaim:
        claimName: openjdk-root-gradle-wrapper-claim
