apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: openjdk
      image: openjdk:11
      command:
      - sleep
      args:
      - 99d
      volumeMounts:
        - mountPath: /test-data/scxa
          name: scxa-ci-data
        - mountPath: /test-data/bioentity_properties
          name: bioentity-properties
        - mountPath: /root/.m2
          name: scxa-ci-build-packages
        - mountPath: /root/.gradle
          name: openjdk-root-gradle-claim
    - name: postgres
      image: postgres:10-alpine
      env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
  volumes:
    - name: scxa-ci-data
      persistentVolumeClaim:
        claimName: scxa-ci-data-claim
    - name: scxa-ci-build-packages
      persistentVolumeClaim:
        claimName: scxa-ci-build-packages-claim
    - name: bioentity-properties
      persistentVolumeClaim:
        claimName: bioentity-properties-claim