version: "3.6"

services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:11-alpine
    networks:
      - atlas-test-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -c max_wal_size=3GB
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  flyway:
    image: flyway/flyway
    networks:
      - atlas-test-net
    depends_on:
      - postgres
    volumes:
      - ../schemas/flyway/${PROJECT_NAME}:/flyway/sql
    command: [
      "-X",
      "-url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}",
      "-schemas=${POSTGRES_USER}",
      "-user=${POSTGRES_USER}",
      "-password=${POSTGRES_PASSWORD}",
      "-target=${SCHEMA_VERSION}",
      "-connectRetries=60",
      "migrate"
    ]

volumes:
  pgdata:
    # Not strictly necessary to error out, but it avoids creating an empty `scxa_postgres-11-pgdata-` volume
    name: ${PROJECT_NAME:?err}_pgdata-${SCHEMA_VERSION:?err}

networks:
  atlas-test-net:
    name: atlas-test-net
