version: "3.6"

services:
  scxa-tomcat:
    image: tomcat:9-jdk11
    container_name: scxa-tomcat
    networks:
      - atlas-test-net
    environment:
      JPDA_ADDRESS: "*:8000"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ../webapps:/usr/local/tomcat/webapps
      - webapp-properties:/webapp-properties
      - bioentity-properties:/atlas-data/bioentity_properties
      - scxa-data:/atlas-data/scxa
      - scxa-tomcat-conf:/usr/local/tomcat/conf
    depends_on:
      - scxa-postgres
      - scxa-solrcloud-0
      - scxa-solrcloud-1
    command: ["catalina.sh", "jpda", "run"]

volumes:
  webapp-properties:
    name: scxa-webapp-properties
  bioentity-properties:
    name: scxa-atlas-data-bioentity-properties
  scxa-data:
    name: scxa-atlas-data-scxa
  scxa-tomcat-conf:
    name: scxa-tomcat-conf

networks:
  atlas-test-net:
    name: atlas-test-net
