version: "3.6"

services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:11-alpine
    networks:
      - atlas-test-net
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -c max_wal_size=3GB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:8
    networks:
      - atlas-test-net
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEMA_VERSION: ${SCHEMA_VERSION}
    command: [
      "-X",
      "-url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}",
      "-schemas=${POSTGRES_USER}",
      "-user=${POSTGRES_USER}",
      "-password=${POSTGRES_PASSWORD}",
      "-target=${SCHEMA_VERSION}",
      "-connectRetries=60",
      "migrate"
    ]
    volumes:
      - ../schemas/flyway/${PROJECT_NAME:?err}:/flyway/sql
    depends_on:
      - postgres

volumes:
  pgdata:
    # Not strictly necessary to error out, but it avoids creating an empty `scxa_postgres-11-pgdata-` volume
    name: ${PROJECT_NAME}_pgdata-${SCHEMA_VERSION:?err}

networks:
  atlas-test-net:
    name: atlas-test-net
