version: "3.6"

services:
  scxa-tomcat:
    image: tomcat:9-jdk11
    container_name: scxa-tomcat
    networks:
      - atlas-test-net
    environment:
      JPDA_ADDRESS: "*:8000"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ../webapps:/usr/local/tomcat/webapps
      - webapp-properties:/webapp-properties
      - bioentity-properties:/atlas-data/bioentity_properties
      - scxa-data:/atlas-data/scxa
      - scxa-expdesign:/atlas-data/scxa-expdesign
      - scxa-tomcat-conf:/usr/local/tomcat/conf
    depends_on:
      - postgres
      - scxa-solrcloud-0
      - scxa-solrcloud-1
    command: ["catalina.sh", "jpda", "run"]

volumes:
  webapp-properties:
    name: ${WEBAPP_PROPERTIES_VOL_NAME}
  bioentity-properties:
    name: ${ATLAS_DATA_BIOENTITY_PROPERTIES_VOL_NAME}
  scxa-data:
    name: ${ATLAS_DATA_SCXA_VOL_NAME}
  scxa-expdesign:
    name: ${ATLAS_DATA_SCXA_EXPDESIGN_VOL_NAME}
  scxa-tomcat-conf:
    name: scxa-tomcat-conf

networks:
  atlas-test-net:
    name: atlas-test-net
