version: "3.6"

services:
  tomcat:
    image: tomcat:9-jdk11
    networks:
      - atlas-test-net
    environment:
      JPDA_ADDRESS: "*:8000"
      JAVA_OPTS: "-Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=${SOLR_USER}:${SOLR_PASSWORD}"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ../webapps:/usr/local/tomcat/webapps
      - ./webapp-properties:/webapp-properties
      - scxa-tomcat-conf:/usr/local/tomcat/conf
      - bioentity-properties:/atlas-data/bioentity_properties
      - exp:/atlas-data/exp
      - expdesign:/atlas-data/expdesign
    depends_on:
      gradle-build:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      solrcloud-0:
        condition: service_started
      solrcloud-1:
        condition: service_started
    command: ["catalina.sh", "jpda", "run"]

volumes:
  gradle-wrapper-dists:
    name: ${PROJECT_NAME:?err}_${GRADLE_WRAPPER_DISTS_VOL_NAME}
  gradle-ro-dep-cache:
    name: ${PROJECT_NAME}_${GRADLE_RO_DEP_CACHE_VOL_NAME}
  scxa-tomcat-conf:
    name: ${PROJECT_NAME}_tomcat-conf
  bioentity-properties:
    name: ${PROJECT_NAME}_${ATLAS_DATA_BIOENTITY_PROPERTIES_VOL_NAME}
  exp:
    name: ${PROJECT_NAME}_${ATLAS_DATA_EXP_VOL_NAME}
  expdesign:
    name: ${PROJECT_NAME}_${ATLAS_DATA_EXPDESIGN_VOL_NAME}

networks:
  atlas-test-net:
    name: atlas-test-net
