version: "3.6"

services:
  scxa-postgres:
    env_file: ./prepare-dev-environment/scxa.env
    image: postgres:11-alpine
    networks:
      - atlas-test-net
    command: -c max_wal_size=2GB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  scxa-flyway:
    env_file: ./prepare-dev-environment/scxa.env
    image: flyway/flyway
    networks:
      - atlas-test-net
    # A trick to interpolate environment variables in Flyway
    # https://github.com/flyway/flyway-docker/issues/11#issuecomment-531272336
    entrypoint: /bin/bash
    command: [
      "-c",
      "/flyway/flyway -url=jdbc:postgresql://$${POSTGRES_HOST}/$${POSTGRES_DB} -schemas=$${POSTGRES_USER} -user=$${POSTGRES_USER} -password=$${POSTGRES_PASSWORD} -connectRetries=60 migrate -target=${SCHEMA_VERSION}"
    ]
    volumes:
      - ../schemas/flyway/scxa:/flyway/sql
    depends_on:
      - scxa-postgres

volumes:
  pgdata:
    name: scxa-postgres-11-pgdata-${SCHEMA_VERSION:-no-schema-specified}

networks:
  atlas-test-net:
      name: atlas-test-net
