version: "3.6"

services:
  scxa-postgres:
    image: postgres:11-alpine
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - atlas-test-net
    command: -c max_wal_size=2GB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  scxa-flyway:
    image: flyway/flyway
    networks:
      - atlas-test-net
    command: [
      "-url=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}",
      "-schemas=${POSTGRES_USER}",
      "-user=${POSTGRES_USER}",
      "-password=${POSTGRES_PASSWORD}",
      "-target=${SCHEMA_VERSION}",
      "-connectRetries=60",
      "migrate"
    ]
    volumes:
      - ../schemas/flyway/scxa:/flyway/sql
    depends_on:
      - scxa-postgres

volumes:
  pgdata:
    # Not strictly necessary to error out, but it avoids creating an empty `scxa-postgres-11-pgdata-` volume
    name: scxa-postgres-11-pgdata-${SCHEMA_VERSION:?err}

networks:
  atlas-test-net:
      name: atlas-test-net
