version: "3.6"

services:
  postgres-test:
    container_name: ${POSTGRES_HOST}
    image: postgres:11-alpine
    networks:
      - atlas-test-net
    ports:
      - "5432:5432"
    command: -c max_wal_size=1GB

  flyway:
    image: flyway/flyway
    networks:
      - atlas-test-net
    depends_on:
      - postgres-test
    volumes:
      - ../schemas/flyway/${PROJECT_NAME}:/flyway/sql
    command: [
      "-url=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}",
      "-schemas=${POSTGRES_USER}",
      "-user=${POSTGRES_USER}",
      "-password=${POSTGRES_PASSWORD}",
      "-target=${SCHEMA_VERSION}",
      "-connectRetries=60",
      "migrate"
    ]

networks:
  atlas-test-net:
    name: atlas-test-net
